- name: Bucardo Multi-master set up
  hosts: sql_servers
  become: yes

  vars_files:
    - vars.yml
  vars:
    ip_node1: "{{ hostvars[ansible_play_hosts[0]]['ansible_host'] }}"
    ip_node2: "{{ hostvars[ansible_play_hosts[1]]['ansible_host'] }}"

  tasks:
    #Installing general packages
    - name: Adding db to 1st node
      script: /home/shntrn/1st_demo/files/bucardo_add_db.sh "{{ ip_node1 }}" "{{ ip_node2 }}" "{{ sync_database }}" "{{ db_user }}" "{{ db_password }}"
      when: ansible_hostname == ansible_play_hosts[0]

    - name: Adding db to 2nd node
      script: /home/shntrn/1st_demo/files/bucardo_add_db.sh "{{ ip_node2 }}" "{{ ip_node1 }}" "{{ sync_database }}" "{{ db_user }}" "{{ db_password }}"
      when: ansible_hostname == ansible_play_hosts[1]

    - name: Adding sync to 1nd node
      script: /home/shntrn/1st_demo/files/bucardo_sync.sh "{{ ip_node1 }}" "{{ ip_node2 }}" "{{ sync_database }}" "{{ db_user }}" "{{ db_password }}"
      when: ansible_hostname == ansible_play_hosts[0]

    - name: Adding db to 2nd node
      shell: bucardo restart
      when: ansible_hostname == ansible_play_hosts[1]





