---
- name: Install Postgres, Init App Db, Bucardo multi-master Sync, Balancer
  hosts: all
  become: yes

  roles:
    - { role: postgres_install, when: "'sql_servers' in group_names" }
    - { role: init_app_db,when: "'sql_servers' in group_names" }
    - { role: bucardo, when: "'sql_servers' in group_names" }
    - { role: sql_balancer, when: "'sql_balancers' in group_names" }
