- name: Bucardo Multi-master set up
  hosts: sql_servers
  become: yes
  vars_files:
    - vars.yml

  tasks:

    - name: Allow md5 connection for the bucardo user in all hosts
      postgresql_pg_hba:
        dest: "/var/lib/pgsql/data/pg_hba.conf"
        contype: host
        address: 192.168.56.1
        databases: all
        method: md5
        users: "{{ sync_db_user }}"
        create: true
      with_items: "{{ ansible_play_hosts }}"
      become: yes
      become_user: postgres

    - name: restart postgres
      service:
        name: postgresql
        state: restarted