- name: Bucardo Multi-master set up
  hosts: sql-balancer
  become: yes

  tasks:

  - name: Debug
    debug:
      msg: "{{hostvars[ item ]}}"
    loop: "{{ groups['sql_servers'] }}"





#  - name: Debug
#    debug:
#      msg: "{{ item }}" #"{{ hostvars[ item ]['ansible_host'] }}"
#    loop: "{{ groups['sql_servers'] }}"

